# permissions for end users to view backups.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: backup-operator
    app.kubernetes.io/managed-by: kustomize
  name: backup-viewer-role
rules:
- apiGroups:
  - operator.kubecenter.com
  resources:
  - backups
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - operator.kubecenter.com
  resources:
  - backups/status
  verbs:
  - get
